### ISSUE TITLE
The stats has stopped updating

### ISSUE THREAD

**Issue by auver** [RBND-studio/fig-stats#10]
After June 13

**Comment by OPesicka** [comment]
Thanks for the heads up! Figma started blocking our data collection.

We fixed the issue on June 14th and have all the data, but there are some issues with backporting them into our database so it might take some time.

On the bright side there shouldn't be any data loss 🤞

**Comment by dijazolagit** [comment]
What is the estimation of when Fig Stats will start displaying data again? Thanks

**Comment by OPesicka** [comment]
Sometime next week

**Comment by dijazolagit** [comment]
Any update so far?

**Comment by OPesicka** [comment]
We are back! Sorry for the delay we had to completely rewrite the app because it wasn't ready for backporting data and other things got in the way.

The data is inconsistent because we were dealing with the blocking so daily scrapes weren't happening exactly 24 hours apart. But we at least have something and from now on it should stabilize.
